services:
  - type: web
    name: portfolio
    runtime: node
    plan: free
    region: singapore
    branch: master
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeployTrigger: commit
